const $ = id => document.getElementById(id);
const screens = ["home","oneCondition","oneForecast","oneInvest","oneOutcome","eightIntro","eightForecast","eightInvest","eightOutcome","eightSummary"];
let oneCondition = "cheap", eightRound = 0, eightType = null, eightHistory = [];
const q = s => 1.5 * s;
const money = x => x.toFixed(1);
function show(id) { screens.forEach(x => $(x).classList.toggle("hidden", x !== id)); }
function setProgress(total=0, done=0) { $("progress").classList.toggle("hidden", total === 0); $("progress").innerHTML = Array.from({length:total}, (_, i) => `<span class="${i < done ? "done" : ""}"></span>`).join(""); }
function updateOneRule() { $("cheap").className = oneCondition === "cheap" ? "selected" : "alt"; $("bond").className = oneCondition === "bond" ? "selected" : "alt"; $("oneRule").textContent = oneCondition === "cheap" ? "The AI promises to return half of its tripled receipt. Breaking the promise has no payoff consequence." : "The same promise is backed by a transparent bond: breaking it transfers 2 × your investment from the AI to you."; }
function updateOneInputs() { const s = Number($("oneInvestment").value); $("oneForecastOut").textContent = `${$("oneForecastInput").value}%`; $("oneInvestmentOut").textContent = s; $("onePromise").textContent = `You invest ${s}. The AI receives ${money(3*s)} and publicly promises to return ${money(q(s))}.`; }
function showOneOutcome() { const s = Number($("oneInvestment").value), p = Number($("oneForecastInput").value)/100, type = Math.random() < .5 ? "honest" : "exploitative"; const returned = type === "honest" || oneCondition === "bond" ? q(s) : 0, kept = s > 0 && returned === q(s), penalty = s > 0 && !kept && oneCondition === "bond" ? 2*s : 0; const you = 10-s+returned+penalty, ai = 3*s-returned-penalty, brier = s === 0 ? "Not applicable" : money((p-(kept?1:0))**2); $("oneResult").innerHTML = `Hidden type revealed: <b>${type}</b>.<br>Return: <b>${money(returned)}</b>; promise compliance: <b>${s===0?"Not applicable":kept?"Kept":"Broken"}</b>.<br>Your payoff: <b>${money(you)}</b>; AI payoff: <b>${money(ai)}</b>; welfare: <b>${money(you+ai)}</b>.<br>Brier score: <b>${brier}</b><p class="small">This is one programmed round, not evidence about people or deployed AI.</p>`; $("benchmark").innerHTML = `<b>One-shot ${oneCondition === "cheap" ? "cheap-talk" : "bond"} result</b><br>The type prior was 50% honest / 50% exploitative. This is the proposal's clean comparison.`; setProgress(4,4); show("oneOutcome"); }
function eightPhase() { return eightRound <= 5 ? "cheap" : "bond"; }
function updateEightInputs() { const s = Number($("eightInvestment").value); $("eightForecastOut").textContent = `${$("eightForecastInput").value}%`; $("eightInvestmentOut").textContent = s; $("eightPromise").textContent = `You invest ${s}. The AI receives ${money(3*s)} and publicly promises to return ${money(q(s))}.`; }
function renderEightLabels() { const phase = eightPhase(), label = `ROUND ${eightRound} OF 8 · ${phase === "cheap" ? "CHEAP TALK" : "TRANSPARENT BOND"}`; ["eightLabel","eightLabel2","eightLabel3"].forEach(id => $(id).textContent = label); $("eightRule").className = `banner${phase === "bond" ? " bond" : ""}`; $("eightRule").innerHTML = phase === "cheap" ? "<b>Cheap-talk rule.</b> Breaking the promise has no payoff consequence." : "<b>Transparent bond is active.</b> Breaking the promise transfers $2s$ from the AI to you."; }
function renderHistory() { if (!eightHistory.length) { $("historyRows").innerHTML = '<tr><td colspan="5" class="small">No completed rounds yet.</td></tr>'; return; } $("historyRows").innerHTML = eightHistory.map(r => `<tr><td>${r.round}</td><td><span class="tag ${r.phase === "bond" ? "bond" : ""}">${r.phase === "bond" ? "Bond" : "Talk"}</span></td><td>${r.forecast}%</td><td>${r.investment}</td><td>${r.compliance}</td></tr>`).join(""); }
function beginEightRound() { eightRound++; $("eightForecastInput").value=50; $("eightInvestment").value=5; renderEightLabels(); updateEightInputs(); setProgress(8,eightRound-1); show("eightForecast"); }
function revealEight() { const s=Number($("eightInvestment").value), forecast=Number($("eightForecastInput").value), bond=eightPhase()==="bond", returned=eightType==="honest"||bond?q(s):0, kept=s>0&&returned===q(s), penalty=s>0&&!kept&&bond?2*s:0, you=10-s+returned+penalty, ai=3*s-returned-penalty, brier=s===0?null:(forecast/100-(kept?1:0))**2, compliance=s===0?"N/A":kept?"Kept":"Broken"; eightHistory.push({round:eightRound,phase:eightPhase(),forecast,investment:s,compliance,brier}); $("eightResult").innerHTML = `The AI type remains hidden until the end.<br>Return: <b>${money(returned)}</b>; promise compliance: <b>${compliance}</b>.<br>Your payoff: <b>${money(you)}</b>; AI payoff: <b>${money(ai)}</b>; welfare: <b>${money(you+ai)}</b>.<br>Brier score: <b>${brier===null?"Not applicable":money(brier)}</b>`; $("eightNext").textContent=eightRound===8?"See session summary":`Continue to Round ${eightRound+1}`; renderHistory(); $("benchmark").innerHTML=`<b>Completed rounds: ${eightHistory.length}/8</b><br>One hidden AI type stays fixed for this learning session.`; setProgress(8,eightRound); show("eightOutcome"); }
const avg=(rows,key)=>rows.length?rows.reduce((x,r)=>x+r[key],0)/rows.length:null;
function showEightSummary() { const phase=kind=>eightHistory.filter(r=>r.phase===kind), stats=rows=>({f:avg(rows,"forecast"),i:avg(rows,"investment"),c:rows.filter(r=>r.compliance==="Kept").length/rows.filter(r=>r.investment>0).length,b:avg(rows.filter(r=>r.brier!==null),"brier")}), a=stats(phase("cheap")),b=stats(phase("bond")), n=x=>x===null||Number.isNaN(x)?"N/A":money(x),pct=x=>x===null||Number.isNaN(x)?"N/A":`${money(x)}%`; $("eightSummaryResult").innerHTML=`<b>Hidden type revealed:</b> ${eightType}.<table class="history"><thead><tr><th>Phase</th><th>Mean forecast</th><th>Mean investment</th><th>Compliance</th><th>Mean Brier</th></tr></thead><tbody><tr><td>Cheap talk (1–5)</td><td>${pct(a.f)}</td><td>${n(a.i)}</td><td>${pct(100*a.c)}</td><td>${n(a.b)}</td></tr><tr><td>Bond (6–8)</td><td>${pct(b.f)}</td><td>${n(b.i)}</td><td>${pct(100*b.c)}</td><td>${n(b.b)}</td></tr></tbody></table><p class="small">This fixed-order extension visualizes learning. A future study must randomize or counterbalance order before making causal claims.</p>`; setProgress(8,8); show("eightSummary"); }
$("chooseOne").addEventListener("click",()=>{ $("sideTitle").textContent="One-shot study"; $("historyWrap").classList.add("hidden"); $("benchmark").textContent="Choose a condition. The one-shot mode is the proposal's primary clean comparison."; updateOneRule(); updateOneInputs(); setProgress(4,1); show("oneCondition"); });
$("chooseEight").addEventListener("click",()=>{ $("sideTitle").textContent="Eight-round extension"; $("historyWrap").classList.remove("hidden"); $("benchmark").textContent="The session history will show your forecasts, investments, and outcomes after each round."; renderHistory(); setProgress(0,0); show("eightIntro"); });
$("cheap").addEventListener("click",()=>{oneCondition="cheap";updateOneRule()}); $("bond").addEventListener("click",()=>{oneCondition="bond";updateOneRule()}); $("oneForecastInput").addEventListener("input",updateOneInputs); $("oneInvestment").addEventListener("input",updateOneInputs); $("oneToForecast").addEventListener("click",()=>{setProgress(4,2);show("oneForecast")}); $("oneBackCondition").addEventListener("click",()=>{setProgress(4,1);show("oneCondition")}); $("oneToInvest").addEventListener("click",()=>{setProgress(4,3);show("oneInvest")}); $("oneBackForecast").addEventListener("click",()=>{setProgress(4,2);show("oneForecast")}); $("oneReveal").addEventListener("click",showOneOutcome);
$("startEight").addEventListener("click",()=>{eightRound=0;eightHistory=[];eightType=Math.random()<.5?"honest":"exploitative";renderHistory();beginEightRound()}); $("eightForecastInput").addEventListener("input",updateEightInputs); $("eightInvestment").addEventListener("input",updateEightInputs); $("eightToInvest").addEventListener("click",()=>{setProgress(8,eightRound-1);show("eightInvest")}); $("eightBackForecast").addEventListener("click",()=>show("eightForecast")); $("eightReveal").addEventListener("click",revealEight); $("eightNext").addEventListener("click",()=>eightRound===8?showEightSummary():beginEightRound()); document.querySelectorAll(".homeButton").forEach(b=>b.addEventListener("click",()=>{setProgress(0,0);show("home")}));
updateOneRule(); updateOneInputs(); updateEightInputs();
